### ISSUE TITLE
Support configurable frontend view engines - Aurelia/Angular2/React etc

### ISSUE THREAD

**Issue by timelf123** [linnovate/mean#1672]
I know this is the 'meAn' stack and some had planned on moving right to angular2 for the next major. Given that Angular 2 is a new framework in a new language and requires significant rewrites to the app code anyway (the migration tooling isn't worth, and API on beta is constantly breaking) this is meant as a discussion re: a configurable frontend engine, and dynamic frontend css template (as designed in the [config#L55](https://github.com/linnovate/mean/blob/master/config/env/default.js#L55))
## Motivation

Make mean.io package system sparkle, separate concerns/views/engines, simplify core meanio module
## Todo (WIP)
- [ ] Move all angular bootstrap/deps to a new `meanio-angular` package
  - [ ] `meanio-angular` can require different mean packages as needed
  - [ ] templates override `meanio-circles meanio-users` etc
- [ ] separate `meanio-material` and `meanio-bootstrap` etc
- [ ] Set config value for frontend package responsible for web bootstrap

Thoughts anyone @linnovate/mean-contributors?

**Comment by liorkesos** [comment]
I like this idea because it's a way to coexist with several front ends (angular-1.x , react, angular2) etc...
So possibly this will introduce a more evolutionary path concerning these types of mean variations.
I would still release 1.0 before taking this road. So we have a clear distinction between the past/present and the future.
Also to meet semver recommendations and because I feel its time...

**Comment by timelf123** [comment]
What does 1.0 look like for you?

**Comment by liorkesos** [comment]
We kind of planned it together :)
That last push , excluding the packages to node_modules, removing
dependencies from linnovate infrastructure, webpack instead of aggregation
and changing the focus to the ecosystem ...
So I think the latest issue cleanups prepare us to do an RC version. Let it
run for 2 weeks and then a beta..
Lior

**Comment by rjVapes** [comment]
My main concern would be what it would do to third party packages with a UI layer.  Even with the bootstrap vs. material it becomes an issue.  If I release a robust module that is fully bootstrap, it likely won't fit into the design of an material site.  I imagine if a package is written with angular etc it would have similar limitations when someone wanted to use it with a package leveraging a different technologies.

If a community thrives off contribution, but only a third or quarter of that contribution is usable by any member it might hurt more than just picking a direction and sticking to it.  We've already had people asking how to downgrade after the material change, for instance.

**Comment by liorkesos** [comment]
Good point...
I've been in this crossroad before with mean and I made the wrong choice assuming Linnovate could lead the opinionated route only to find that we could not invest so much over time in the platform so controling/approving the stack was not feasable.
I think we should start with a small set and move from there.
Before switching front ends I'd rather focus on a modular way to reduce mean to run just node and express with multiple data sources and to make it a valid choice to use in microservice architectures.
So If someone wants to lead the multiple front end approach I'm pro choice but I think that product roadmap should be focused on the modularity, speed and security of it's core components..
